---
title: "EMA, Grazia Mirabito"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r, cleaning data}
knitr::opts_chunk$set(echo = TRUE)
#import packages
library (ggplot2)
library(dplyr)
library(psych)
library(plyr)
library(doBy)
library(lme4)
library(jtools)

#import data
data <- readxl::read_xlsx("~/Desktop/Thesis/Aggregating-EMA/Long-Format.xlsx")

#recodedata
data$PhysicalActivity<- recode(data$PhysicalActivity, "YES"= 1, "NO"= 2)

#look at stats before aggregating
#describe(data)

#parsing the timestamp string to just have the date mm/dd
data$DATE <- substr(data$TIMESTAMP, 1, 10)

#sort new data and aggregate #getting average of scores by date and id 
new.data1 <- summaryBy(GROUP + TMS + Curiousity + Decentering + STRESSOR + PROMIS + PWB + Rumination + SLEEP + PhysicalActivity + FORMAL + INFORMAL ~ DATE + ID, data=data, FUN=mean, na.rm=T)

#make date numeric and not a string
new.data1$DATE <- as.Date(new.data1$DATE, "%m/%d/%Y")

describe(new.data1)
#exporting file
library("writexl")
#write_xlsx(new.data1,"~/Desktop/average-Long-Format.xlsx")
```

``` {r, cronbach data cleaning}
chron <- readxl::read_xlsx("~/Desktop/Thesis/Aggregating-EMA/TOGETHER-EMA.xlsx")

#getting the last data point for the morning survey 
chron.new <- unique(chron$ID)
a<-length(chron.new) 
last <- c()
for (i in 1:a) {
  temp<-subset(chron, ID==chron.new[i])
  if (dim(temp)[1] > 1) {
    last.temp<-temp[dim(temp)[1],]
  }
  else {
    last.temp<-temp
  }
  last<-rbind(last, last.temp)
}

as.data.frame(last)

#getting the first data point for the morning survey 
t.first <- chron[match(unique(chron$ID), chron$ID),]
as.data.frame(t.first)

#exporting 
#write_xlsx(last,"~/Desktop/average-last.xlsx")
#write_xlsx(t.first,"~/Desktop/average-first.xlsx")

```


```{r, empty model}
#cleaned data in excel to get day of study numbers 
#importing new data 
EMA <- readxl::read_xlsx("~/Desktop/Thesis/Aggregating-EMA/EMA-Final.xlsx")
#recode group to 0 and 1 
#0= control 1= intervention
EMA$GROUP.mean <- recode(EMA$GROUP.mean, "1"=0 , "2"=1 )
#reode day to start with 0-34
EMA$DAY2 <- (EMA$DAY-1)

#visualize data
#level 1== day 
#level 2== people 
#level 3== group (control vs intervention)

#get ICC of within a person dependence for mindfulness
Mindfulness<- lmer(TMS.mean ~ 1 + (1 |ID), data = EMA,REML = TRUE)
summ(Mindfulness)

#ICC of within group dependence for curiousity
Curiousity <- lmer(Curiousity.mean ~ 1 + (1 |ID), data = EMA,REML = TRUE)
summ(Curiousity)

#ICC of within group dependence for decentering
Decentering <- lmer(Decentering.mean ~ 1 + (1 |ID), data = EMA,REML = TRUE)
summ(Decentering)

#ICC of within group dependence for stressor
Stressor <- lmer(STRESSOR.mean ~ 1 + (1 |ID), data = EMA,REML = TRUE)
summ(Stressor)

#ICC of within group dependence for promis
Promis <- lmer(PROMIS.mean ~ 1 + (1 |ID), data = EMA,REML = TRUE)
summ(Promis)

#ICC of within group dependence for well being
PWB <- lmer(PWB.mean ~ 1 + (1 |ID), data = EMA,REML = TRUE)
summ(PWB)

#ICC of within group dependence for rumination
Rumination <- lmer(Rumination.mean ~ 1 + (1 |ID), data = EMA,REML = TRUE)
summ(Rumination)

#ICC of within group dependence for sleep
Sleep <- lmer(SLEEP.mean ~ 1 + (1 |ID), data = EMA,REML = TRUE)
summ(Sleep)

#ICC of within group dependence for PA
PA <- lmer(PhysicalActivity.mean ~ 1 + (1 |ID), data = EMA,REML = TRUE)
summ(PA)

```
**I ran multiple empty models of time on outcome variables by participant ID, the ICC's for within a person ranged from 0.25-0.74, making the DE range from 30-86.84, therefore, multilevel modelling would be good to do to account for the nesting of the data.** 

```{r, visualize data}
#plot and visualize each outcome by running OLS for each... this is one option. second option using ggplot is in next section  
#visualize TMS 
OLS <- lmList(TMS.mean ~ DAY2 | ID , data= EMA)
OLS
plot (EMA$DAY, EMA$TMS.mean) 
for (i in 1:114){
  abline(a = coef(OLS)[i,1], b = coef(OLS)[i,2])
}

#visualize curiosity 
OLS1 <- lmList(Curiousity.mean ~ DAY2 | ID , data= EMA)
OLS1
plot (EMA$DAY, EMA$Curiousity.mean) 
for (i in 1:114){
  abline(a = coef(OLS1)[i,1], b = coef(OLS1)[i,2])
}

#visualize Decentering 
OLS2 <- lmList(Decentering.mean ~ DAY2 | ID , data= EMA)
OLS2
plot (EMA$DAY, EMA$Decentering.mean) 
for (i in 1:114){
  abline(a = coef(OLS2)[i,1], b = coef(OLS2)[i,2])
}

#visualizing stress
OLS3 <- lmList(STRESSOR.mean ~ DAY2 | ID , data= EMA)
OLS3
plot (EMA$DAY, EMA$STRESSOR.mean) 
for (i in 1:114){
  abline(a = coef(OLS3)[i,1], b = coef(OLS3)[i,2])
}

#visualizing anxiety (promis)
OLS4 <- lmList(PROMIS.mean ~ DAY2 | ID , data= EMA)
OLS4
plot (EMA$DAY, EMA$PROMIS.mean) 
for (i in 1:114){
  abline(a = coef(OLS4)[i,1], b = coef(OLS4)[i,2])
}

#visualizing well being 
OLS5 <- lmList(PWB.mean ~ DAY2 | ID , data= EMA)
OLS5
plot (EMA$DAY, EMA$PWB.mean) 
for (i in 1:114){
  abline(a = coef(OLS5)[i,1], b = coef(OLS5)[i,2])
}

#viualizing rumination 
OLS6 <- lmList(Rumination.mean ~ DAY2 | ID , data= EMA)
OLS6
plot (EMA$DAY, EMA$Rumination.mean) 
for (i in 1:114){
  abline(a = coef(OLS6)[i,1], b = coef(OLS6)[i,2])
}

#sleep 
OLS7 <- lmList(SLEEP.mean ~ DAY2 | ID , data= EMA)
OLS7
plot (EMA$DAY, EMA$SLEEP.mean) 
for (i in 1:5){
  abline(a = coef(OLS7)[i,1], b = coef(OLS7)[i,2])
}

#PA 
OLS8 <- lmList(PhysicalActivity.mean ~ DAY2 | ID , data= EMA)
OLS8
plot (EMA$DAY, EMA$PhysicalActivity.mean) 
for (i in 1:5){
  abline(a = coef(OLS8)[i,1], b = coef(OLS8)[i,2])
}
```


```{r, visualize with ggplot}

plot1 <- ggplot(data=EMA, aes(x=DAY, y=TMS.mean, group=ID)) + geom_line() + theme_bw() + scale_x_continuous(breaks = 1:35, name = "Day") + scale_y_continuous(name = "TMS")
plot1

plot2 <- ggplot(data=EMA, aes(x=DAY, y=Decentering.mean, group=ID)) + geom_line() + theme_bw() + scale_x_continuous(breaks = 1:35, name = "Day") + scale_y_continuous( name = "Decentering")
plot2

plot3 <- ggplot(data=EMA, aes(x=DAY, y=Curiousity.mean, group=ID)) + geom_line() + theme_bw() + scale_x_continuous(breaks = 1:35, name = "Day") + scale_y_continuous( name = "Curiousity")
plot3

plot4 <- ggplot(data=EMA, aes(x=DAY, y=STRESSOR.mean, group=ID)) + geom_line() + theme_bw() + scale_x_continuous(breaks = 1:35, name = "Day") + scale_y_continuous( name = "Stressor")
plot4

plot5 <- ggplot(data=EMA, aes(x=DAY, y=PROMIS.mean, group=ID)) + geom_line() + theme_bw() + scale_x_continuous(breaks = 1:35, name = "Day") + scale_y_continuous( name = "PROMIS")
plot5

plot5 <- ggplot(data=EMA, aes(x=DAY, y=PWB.mean, group=ID)) + geom_line() + theme_bw() + scale_x_continuous(breaks = 1:35, name = "Day") + scale_y_continuous( name = "PWB")
plot5

plot6 <- ggplot(data=EMA, aes(x=DAY, y=Rumination.mean, group=ID)) + geom_line() + theme_bw() + scale_x_continuous(breaks = 1:35, name = "Day") + scale_y_continuous( name = "Rumination")
plot6

plot7 <- ggplot(data=EMA, aes(x=DAY, y=SLEEP.mean, group=ID)) + geom_line() + theme_bw() + scale_x_continuous(breaks = 1:35, name = "Day") + scale_y_continuous( name = "Sleep")
plot7

plot8 <- ggplot(data=EMA, aes(x=DAY, y=PhysicalActivity.mean, group=ID)) + geom_line() + theme_bw() + scale_x_continuous(breaks = 1:35, name = "Day") + scale_y_continuous( name = "Physical Activity")
plot8
```

```{r, Cronbach Alpha}



```

```{r, run stats INCOMPLETE} 
#running stats 
#center variables 
library(robumeta)
EMA$TMS.center <- group.center(EMA$TMS.mean, EMA$ID) 
#run model of change of TMS over time.
#Ran.Slopes <- lmer(TMS.mean ~ 1 + (1 |ID), data = EMA,REML = TRUE)
#summary(Ran.Slopes)
#summ(Ran.Slopes)

```





